# Generated by Django 5.0.2 on 2026-07-19 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0001_initial"),
        ("room", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_reserved", models.DateField()),
                ("checkin_shift", models.BooleanField(default=True)),
                ("nights", models.IntegerField(default=0)),
                ("days", models.IntegerField(default=0)),
                ("checkout_shift", models.BooleanField(default=True)),
                ("is_canceled", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "guest_related",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guest_reservation",
                        to="account.guest",
                    ),
                ),
                (
                    "room_related",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_reservation",
                        to="room.room",
                    ),
                ),
            ],
        ),
    ]
