# Generated by Django 5.0.2 on 2026-07-20 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="date_reserved",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="days",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="is_canceled",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="nights",
        ),
        migrations.AddField(
            model_name="reservation",
            name="checkin_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reservation",
            name="checkout_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reservation",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("submitted", "Submitted"),
                    ("approved", "Approved"),
                    ("canceled", "Canceled"),
                ],
                default="submitted",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="checkin_shift",
            field=models.CharField(
                choices=[("day", "Day"), ("night", "Night"), ("fullday", "Fullday")],
                default="day",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="checkout_shift",
            field=models.CharField(
                choices=[("day", "Day"), ("night", "Night"), ("fullday", "Fullday")],
                default="day",
                max_length=20,
            ),
        ),
    ]
