# Generated by Django 5.0.2 on 2026-07-23 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0002_remove_reservation_date_reserved_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="checkin_shift",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="checkout_shift",
        ),
    ]
