# Generated by Django 5.0.2 on 2026-07-15 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(blank=True, max_length=200, null=True)),
                ("lastname", models.CharField(blank=True, max_length=200, null=True)),
                ("email", models.EmailField(max_length=254)),
                (
                    "phone",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=11, null=True
                    ),
                ),
                ("img", models.ImageField(blank=True, null=True, upload_to="avatars")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_code", models.CharField(max_length=10)),
                ("job_title", models.CharField(max_length=200)),
                ("address", models.TextField()),
                (
                    "phone",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=11, null=True
                    ),
                ),
                (
                    "national_id",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=11, null=True
                    ),
                ),
                (
                    "account_related",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_account",
                        to="account.account",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Guest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("passport_img", models.ImageField(upload_to="media/guest/passport")),
                (
                    "nationalcard_img",
                    models.ImageField(upload_to="media/guest/nationalcard"),
                ),
                ("phone", models.DecimalField(decimal_places=0, max_digits=11)),
                ("address", models.TextField()),
                (
                    "account_related",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guest_account",
                        to="account.account",
                    ),
                ),
            ],
        ),
    ]
