# Generated by Django 5.0.2 on 2026-07-16 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RoomType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("Standard", "Standard"),
                            ("Deluxe", "Deluxe"),
                            ("Suite", "Suite"),
                            ("Presidential", "Presidential"),
                        ],
                        default="Standard",
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("bed_count", models.IntegerField(default=0)),
                ("description", models.TextField()),
                ("area", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_code", models.DecimalField(decimal_places=0, max_digits=11)),
                (
                    "room_status",
                    models.CharField(
                        choices=[
                            ("available", "available"),
                            ("Occupied", "Occupied"),
                            ("repairing", "repairing"),
                            ("Reserved", "Reserved"),
                        ],
                        default="available",
                        max_length=100,
                    ),
                ),
                ("price", models.PositiveIntegerField(default=0)),
                ("floor", models.PositiveIntegerField(default=0)),
                (
                    "roomtype_related",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="type_room",
                        to="room.roomtype",
                    ),
                ),
            ],
        ),
    ]
